### PR TITLE
An absolutely massive number of improvements.

### PR DESCRIPTION
**Pull request by nhubbard**
Hi there!
I am a big fan of your version of the game - it's one of the best out there!

Since I use Linux as my daily driver, I decided to a) upgrade this project to use .NET Core, b) give it a complete run-down with my copy of ReSharper Ultimate (in their Rider IDE), and c) replace any platform-specific code with generic code that works wherever the project is run.

As all major refactoring projects progress, their goals change; and so, my changes are as follows:

1. **Upgrading Nancy to the latest version.** Nancy was not compatible with .NET Core until major release 2.0.0. With 2.0.0, they changed the routing syntax and some details about view handling. I refactored the Web modules to use the new routing and view syntax, and ensured that the application worked just as well as it did before I made the changes after completing this task.
2. **Eliminating HTMLAgilityPack.** They made a new major release without providing a migration guide, including eliminating a function which was our almost sole usage of it. I replaced it with HTMLSanitizer, a much simpler project which fits our needs while reducing code complexity.
3. **Replacing platform-specific code.** This came down to replacing the PostBuildTask in the project file with a universal ItemTask which copies the `web_content` and `packs` folders, along with the `settings.json` file to the output directory without relying on Windows-specific command line functionality.
4. **Improving documentation.** I fixed a lot of information in the README file, jazzing it up with a little bit more sarcasm along the way. I also fixed the random license files scattered about. We don't need to have 4 license files with the same license repeated over and over again, so I replaced it with 1 file. I'm still working on improving the pack, taunt and trophy documentation, though.
5. **ReSharper.** This, by far, was the biggest change. I ran ReSharper on the project and fixed many (as it calls them) "warnings", "suggestions" and "hints" like feature usage, auto-property usage, redundant `using` statements, and so on.

Let me know what you think! I really hope that you like the changes and are willing to merge them.

### CODE REVIEW

**Comment by TheBerkin** [comment]
Thanks for the PR! I'm particularly impressed by the .NET Core compatibility-- this would be a huge plus for the project. Excellent work.

I'll check over your changes in my spare time and and get back to you as soon as my work schedule allows.

**Comment by TheBerkin** [comment]
Just noticed: It looks like you forked the `master` branch, but I currently have more changes on the `beta4` branch that would have to be merged as well. If possible, could you include those changes in your PR as well?

**Comment by nhubbard** [comment]
Sure, I can take a look at that. Thanks!

**Comment by nhubbard** [comment]
Okay. I took a quick look at some of the changes in beta 4. Right now, the changing of the method signatures won't work until we add some sort of value for it. ReSharper had an absolute fit when I changed the method signature and didn't add a new parameter, instead leaving "TODO" in the new parameter when I changed the method signature. Did we change the calls to the functions after changing the signatures?

We have two options:
* Merge this pull request, rebase onto the beta 4, and fix any resulting problems
* Finish beta 4, then merge changes via two separate pull requests

Which would you prefer?

**Comment by TheBerkin** [comment]
I will prepare Beta 4 for release as a smaller update (partially for the sake of making this easier to merge). I'll then merge it into `master` and we can then take a look at what needs to be changed in order to merge your changes.

**Comment by TheBerkin** [comment]
Your changes are (tentatively) merged on Beta 5. Going to check over it in VS now to make sure I didn't break anything too badly.

**Comment by nhubbard** [comment]
Sounds good. I also do have the new base deck available for the decks repository because I recently bought the new 2.0 revision of the base game.

**Comment by TheBerkin** [comment]
The CoLAN port of the CAH deck should already be updated to 2.0, IIRC. I can double-check.

I noticed that there are still a lot of dependencies for .NET Framework libraries. Will this interfere with server functionality on non-Windows machines?

**Comment by nhubbard** [comment]
It won't affect functionality. The `dotnet` executable just throws a bunch of warnings about it and lets it slide.

**Comment by nhubbard** [comment]
Should I close my PR and re-base it on the `beta5` branch?

**Comment by TheBerkin** [comment]
I think that would be the best option here.

**Pull request closed without merging**
